### ISSUE TITLE
Facebook agent message tag

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/rapidpro#4486]
When messaging from the ticket interface (or the contact tab for that matter) we should use the human agent tag for Facebook messages which allows up to 7 days to respond instead of one.

> For messaging flows that require an escalation path, the Human Agent tag allows a business representative to manually respond to a person’s messages within a 7-day period.

More here:
https://developers.facebook.com/docs/messenger-platform/send-messages

**Comment by rowanseymour** [comment]
When is it appropriate to use this? Obviously when replying to a ticket.. but also when just chatting from a contact read page right? But if a user sends a message to 2 contacts as a broadcast.. then no?

**Comment by rowanseymour** [comment]
In mailroom, we can look at a message to see if it's not from a flow or a broadcast - which would imply it came from chat. However that's just how we use the messages endpoint internally and somebody could be hitting the messages endpoint with content that isn't suitable for a facebook agent tag. Maybe we add a `human=true|false` field to the messages endpoint which generally determines how channels should treat it?

Something else to consider is that the FB agent tag is only applicable if you're replying within 7 days of an incoming message. So what do we do when we think you're outside of that window? We can certainly warn users in the UI - we can look for an FB/IG URN and look at `last_seen_on` and show a warning if they're out of the 7 day window.

Maybe we also queue messages to courier with the contact last_seen_on and let the courier FB channel decide if it's appropriate to use the agent tag... or we just use it anyway because users have been warned the message might not send?
